name: heroes_apir
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.5
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  
  fonts:
      - family: LuckiestGuy
        fonts:
          - asset: assets/fonts/Luckiest_Guy/LuckiestGuy-Regular.ttf
      - family: Marcellus
        fonts:
          - asset: assets/fonts/Marcellus_SC/MarcellusSC-Regular.ttf
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf

  assets:
    - assets/database/heroes_apir.db